version: '3.1'
services:
  db:
    image: postgres
    container_name: springboot_postgres_container
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root
    ports:
      - "3306:3306"
    volumes:
      - spring_data:/var/lib/postgresql

volumes:
  spring_data: